title: MiaadZ | S3Z4R
description: Offensive Security Portfolio & CTF Writeups.
remote_theme: "mmistakes/minimal-mistakes@4.27.3"

# Removes the Github Profile Button
aux_links:
  "GitHub Profile":
    - //github.com/MiaadZ

# Color Scheme
color_scheme: dark

# Search settings
search_enabled: true
