title: "S3Z4R | Cybersecurity Portfolio"
description: "Offensive Security & Penetration Testing Writeups"

# Navigation
search: true
search_provider: lunr
url: "https://MiaadZ.github.io"

# Theme Settings
remote_theme: "mmistakes/minimal-mistakes@4.27.3"
minimal_mistakes_skin: "dark"

# Plugins
plugins:
  - jekyll-include-cache

# Populate Pages
collections:
  pages:
    output: true
    sort_by: date

# Sidebar Settings
defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: "main"

include: ["TryHackMe", "HackTheBox"]