title: "S3Z4R | Cybersecurity Portfolio"
description: "Offensive Security & Penetration Testing Writeups"
url: "https://MiaadZ.github.io"
baseurl: ""

# Theme Settings
remote_theme: "mmistakes/minimal-mistakes@4.27.3"
minimal_mistakes_skin: "dark"

# Plugins
plugins:
  - jekyll-include-cache

# Navigation & Search (Disabled)
search: false

# Author / Sidebar Profile
author:
  name: "MiaadZ (S3Z4R)"
  avatar: "/assets/images/profile.png"
  bio: "Offensive Security<br>Penetration Testing<br>Top 7% @ TryHackMe"
  location: "Germany"
  links:
    - label: "TryHackMe"
      icon: "fas fa-flag"
      url: "https://tryhackme.com/p/S3Z4R"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/MiaadZ"

# Global Page Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: "main"
      # No Comments!
      comments: false 

# Collections to Include
include: ["TryHackMe", "HackTheBox"]