title: "S3Z4R | Cybersecurity Portfolio"
description: "Offensive Security & Penetration Testing Writeups"
url: "https://MiaadZ.github.io" 

# Theme Settings
remote_theme: "mmistakes/minimal-mistakes@4.27.3"
minimal_mistakes_skin: "dark"

# Plugins
plugins:
  - jekyll-include-cache

# Navigation
search: true

# Sidebar Settings
defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: "main"
      classes: wide

include: ["TryHackMe", "HackTheBox"]